import type { Metadata } from "next";
import { PolicyPage } from "@/components/marketing/policy-page";

export const metadata: Metadata = {
  title: "Terms",
  description:
    "The terms on which Retail Intelligence AI is provided, including what the product does and does not claim to do.",
};

export default function TermsPage() {
  return (
    <PolicyPage
      title="Terms of service"
      summary="What you can expect from the product, and what it does not claim to be."
      updatedAt="August 2026"
      sections={[
        {
          heading: "What the service provides",
          paragraphs: [
            "Retail Intelligence AI records your business transactions and derives accounting records, financial statements, tax and GST working papers, analytics and forecasts from them.",
          ],
        },
        {
          heading: "What it is not",
          paragraphs: [
            "This is the most important section on this page, and it is stated plainly rather than buried.",
          ],
          bullets: [
            "It is not a filing service. GST and income tax returns are prepared for your review and marked as such. Filing is done by you or your representative through the official portals.",
            "It is not professional advice. Nothing the product produces — including anything generated by its AI features — is tax, legal, accounting or audit advice, and it does not replace a qualified professional.",
            "The AI Auditor identifies anomalies and risks for review. It does not determine that fraud, error or non-compliance has occurred, and its findings are not an audit opinion.",
            "Forecasts are projections from your own historical data, presented as ranges. They are not a guarantee of future results.",
            "The financial health score is an internal indicator. It is not a credit score, is not regulated, and is not reported to any bureau.",
          ],
        },
        {
          heading: "Your responsibilities",
          bullets: [
            "The accuracy of your records depends on the accuracy of what you enter. The system enforces internal consistency; it cannot know that a figure you typed was wrong.",
            "You are responsible for reviewing prepared returns and statements before relying on or submitting them.",
            "You are responsible for keeping your sign-in credentials confidential and for the actions of the users you invite.",
          ],
        },
        {
          heading: "Accounts and access",
          bullets: [
            "You must provide accurate registration details and keep them current.",
            "You may invite additional users and assign them roles. Each role grants a specific set of permissions, and you remain responsible for who you grant access to.",
            "We may suspend an account for non-payment, or where use of the service threatens its security or availability for others.",
          ],
        },
        {
          heading: "Subscriptions and billing",
          bullets: [
            "Plans are billed in advance for the selected interval. A free trial converts to a paid subscription only when you choose a plan.",
            "You may change or cancel your plan at any time. Cancellation takes effect at the end of the current billing period.",
            "If a subscription lapses, your account becomes read-only rather than being deleted, and export remains available.",
          ],
        },
        {
          heading: "Data integrity",
          paragraphs: [
            "Posted financial records are immutable by design. Corrections are made through reversing entries or voids, both of which are recorded with a reason and remain visible in your audit trail. This is a deliberate constraint that preserves the defensibility of your books.",
          ],
        },
        {
          heading: "Availability",
          paragraphs: [
            "We aim for continuous availability, but the service may be unavailable during maintenance or as a result of events outside our control. Where a target service level applies to your plan, it is stated in your subscription.",
          ],
        },
        {
          heading: "Changes to these terms",
          paragraphs: [
            "Material changes will be notified in the application and by email before they take effect. Continuing to use the service after that point constitutes acceptance.",
          ],
        },
      ]}
    />
  );
}
