/**
 * Stable identifiers for the ledgers the accounting engine posts to.
 *
 * The engine resolves accounts by `systemKey`, never by name or code, so a
 * retailer renaming "Cash" to "Counter Cash" or renumbering their chart of
 * accounts cannot silently break posting rules.
 */
export const SYSTEM_ACCOUNT = {
  // Assets
  CASH: "CASH",
  BANK: "BANK",
  ACCOUNTS_RECEIVABLE: "ACCOUNTS_RECEIVABLE",
  INVENTORY: "INVENTORY",
  FIXED_ASSETS: "FIXED_ASSETS",
  ACCUMULATED_DEPRECIATION: "ACCUMULATED_DEPRECIATION",
  PREPAID_EXPENSES: "PREPAID_EXPENSES",
  GST_INPUT_CGST: "GST_INPUT_CGST",
  GST_INPUT_SGST: "GST_INPUT_SGST",
  GST_INPUT_IGST: "GST_INPUT_IGST",
  GST_INPUT_CESS: "GST_INPUT_CESS",

  // Liabilities
  ACCOUNTS_PAYABLE: "ACCOUNTS_PAYABLE",
  GST_OUTPUT_CGST: "GST_OUTPUT_CGST",
  GST_OUTPUT_SGST: "GST_OUTPUT_SGST",
  GST_OUTPUT_IGST: "GST_OUTPUT_IGST",
  GST_OUTPUT_CESS: "GST_OUTPUT_CESS",
  GST_PAYABLE: "GST_PAYABLE",
  TDS_PAYABLE: "TDS_PAYABLE",
  SALARY_PAYABLE: "SALARY_PAYABLE",
  ACCRUED_EXPENSES: "ACCRUED_EXPENSES",
  LOANS_PAYABLE: "LOANS_PAYABLE",

  // Equity
  OWNER_CAPITAL: "OWNER_CAPITAL",
  DRAWINGS: "DRAWINGS",
  RETAINED_EARNINGS: "RETAINED_EARNINGS",

  // Income
  SALES: "SALES",
  SALES_RETURNS: "SALES_RETURNS",
  DISCOUNT_ALLOWED: "DISCOUNT_ALLOWED",
  OTHER_INCOME: "OTHER_INCOME",
  ROUND_OFF: "ROUND_OFF",

  // Cost of sales
  PURCHASES: "PURCHASES",
  PURCHASE_RETURNS: "PURCHASE_RETURNS",
  COST_OF_GOODS_SOLD: "COST_OF_GOODS_SOLD",
  DISCOUNT_RECEIVED: "DISCOUNT_RECEIVED",
  DIRECT_EXPENSES: "DIRECT_EXPENSES",
  OPENING_STOCK: "OPENING_STOCK",
  CLOSING_STOCK: "CLOSING_STOCK",

  // Operating expenses
  SALARY_EXPENSE: "SALARY_EXPENSE",
  RENT_EXPENSE: "RENT_EXPENSE",
  ELECTRICITY_EXPENSE: "ELECTRICITY_EXPENSE",
  WATER_EXPENSE: "WATER_EXPENSE",
  INTERNET_EXPENSE: "INTERNET_EXPENSE",
  TELEPHONE_EXPENSE: "TELEPHONE_EXPENSE",
  FUEL_EXPENSE: "FUEL_EXPENSE",
  ADVERTISEMENT_EXPENSE: "ADVERTISEMENT_EXPENSE",
  REPAIRS_EXPENSE: "REPAIRS_EXPENSE",
  MAINTENANCE_EXPENSE: "MAINTENANCE_EXPENSE",
  INSURANCE_EXPENSE: "INSURANCE_EXPENSE",
  BANK_CHARGES: "BANK_CHARGES",
  TRANSPORTATION_EXPENSE: "TRANSPORTATION_EXPENSE",
  OFFICE_EXPENSE: "OFFICE_EXPENSE",
  PROFESSIONAL_FEES: "PROFESSIONAL_FEES",
  MISCELLANEOUS_EXPENSE: "MISCELLANEOUS_EXPENSE",
  DEPRECIATION_EXPENSE: "DEPRECIATION_EXPENSE",
  INTEREST_EXPENSE: "INTEREST_EXPENSE",
} as const;

export type SystemAccountKey =
  (typeof SYSTEM_ACCOUNT)[keyof typeof SYSTEM_ACCOUNT];
